wizardry_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: WizardryUserBundle:Default:index }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
