# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: MainBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    sonata.user.serializer.handler.user:
         class: Sonata\UserBundle\Serializer\UserSerializerHandler
         tags:
         - { name: jms_serializer.subscribing_handler }
         arguments:
         - [ sonata.user.mongodb.user_manager ]